# Generated by Django 3.0.8 on 2020-07-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_avg', models.FloatField()),
                ('hum_max', models.FloatField()),
                ('hum_min', models.FloatField()),
                ('hum_avg', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Sensor',
            },
        ),
    ]
